# Generated by Django 4.2.6 on 2023-12-06 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
